### ISSUE TITLE
Hard crash when encountering an invalid xml file

### ISSUE THREAD

**Issue by jholland-usgs** [iris-edu/stationxml-validator#89] opened 2019-12-10 20:57 UTC
If I run the validator on a folder containing metadata files and one file is invalid. It will crash hard and not check the remaining files.
In my case I am running this against ~300 files at a time, executing the jar once per file is an inconvenience.

It would be friendlier behavior to log/print an error and continue validating the rest.

**Comment by jholland-usgs** [comment] 2019-12-10 21:29
I have coded up a simple fix that logs and prints out the exception to stderr (not sure if that is the best place).
https://github.com/jholland-usgs/stationxml-validator/blob/1e16e526a7cedcc1afb473bd26f14e6356653fda/src/main/java/edu/iris/dmc/Application.java#L143-L175

**Comment by yazan-iris** [comment] 2020-03-19 18:14
A more appropriate measure is to have the user choose to ignore errors, maybe --continue-on-error flag.  Exceptions/Errors should be ignored by default, Exception/Errors here refer to file/rules and not application Exceptions/Errors.

**Comment by timronan** [comment] 2020-03-19 19:03
The logic from 
https://github.com/jholland-usgs/stationxml-validator/blob/1e16e526a7cedcc1afb473bd26f14e6356653fda/src/main/java/edu/iris/dmc/Application.java#L143-L175
 has been adapted and is embedded in pull request [#98](https://github.com/iris-edu/stationxml-validator/pull/98). We will add the flag --continue-on-error use this logical pattern. 

@yazan-iris 

>  Exceptions/Errors should be ignored by default

Do you mean file/rule Exceptions/Errors should not be ignored by default? If the quote is accurate  and not a typeo the flag should read --stop-on-error.

**Comment by timronan** [comment] 2020-04-27 23:10
Validator version [stationxml-validator-1.7.0-RC-01](https://github.com/iris-edu/stationxml-validator/releases/tag/stationxml-validator-1.7.0-RC-01), available on the Validator's releases page, includes the --continue-on-error flag that prevents the validator from crashing if an error is encountered. Only use this flag when validating directories of metadata. 

java -jar stationxml-validator-1.7.0.jar /path/to/metadata --continue-on-error 

The --verbose flag has also been included into stationxml-validator-1.7.0-RC-01. The verbose flag prints the name of the validated file before the validation report. 

java -jar stationxml-validator-1.7.0.jar /path/to/metadata --continue-on-error --verbose

Please verify these functions work satisfactorily and report or close the issue based on your findings.

**Comment by jholland-usgs** [comment] 2020-04-28 23:42
I have tested using latest source build at commit 5c67d27e955354284b6b04eb0e072ca627ffe6cd
1. --continue-on-error  This worked as expected during the tests.
```java -jar stationxml-validator-1.7.0.jar /path/to/metadata --continue-on-error```
2. --verbose This made no difference in output when testing.
It was executed similar to the example given. 
``` java -jar stationxml-validator-1.7.0.jar /path/to/metadata --continue-on-error --verbose```

I can provide exact outputs if needed.

**Comment by timronan** [comment] 2020-04-28 23:54
Did --verbose not print out the name of the input file similar to:
```
[2020-04-28 16:51:55] [INFO  ] edu.iris.dmc.Application read: Input file: ./src/test/resources/pass.xml 
```
 Running the validator without the --verbose flag should not provide the additional information shown above. Does the released validator instance work differently than this?

**Comment by jholland-usgs** [comment] 2020-04-28 23:55
Further testing of --verbose did produce an expected response from --verbose, but it was directed into the stderr output. This is workable since a user can redirect stderr into stdout if logging outputs.

**Closed** 2020-04-28 23:59 UTC

**Comment by timronan** [comment] 2020-04-29 00:11
That is a known issue that I don't really like either. The problem is that  java.util.logging prints INFO messages to stderr rather than stdout by default. The output stream for INFO can be changed but than WARNING AND SEVERE are printed to stdout. We also thought about changing the logging level to debug that but than other additional information pollutes the validators output. We kind of decided the best solution was printing those messages to stderr and redirecting into stdout as you suggested above. I will clarify this in the documentation, thanks for reminding us. 

https://stackoverflow.com/questions/34156052/why-does-java-util-logging-logger-print-to-stderr

**Comment by rcasey-iris** [comment] 2020-04-29 15:22
Two cents:
	I think this is done by design.  You always want users to see severe errors and warnings.  It's critical feedback that the user must generally see.  Verbose output is all INFO level material for tracing that is better sent to a different channel so you have the option to log it instead of displaying it.  As you've indicated, you can choose to tie the two together to have the user see everything, and this could be a component of using the verbose flag, maybe a different level.
